$(document).ready(function() {

  var quotes = ["I did the Kessel run in less than 12 parsecs.", "One of my greatest passions is learning languages. Apart from Portuguese, I have also studied a bit of French, German, Spanish and English. Japanese is the next on the list.", "I have lived/ worked in Brazil, Chile, England and Singapore.","When I was in first year of Design school I was unhappy with my learnings and applied for the Architecture and Urbanism course. I'm extremely happy I didn't change my mind at that time.", "I am currently re-reading Blink by Malcolm Gladwell.","John Maeda's Laws of simplicity book is one of my personal mantras.","It sounds cliché, but I believe in Rams' Less but Better motto as a lifestyle. I am currently listing everything I own and so I can cut it down to 300 objects. Wish me luck!","I'm only 1,76m tall but I played volleyball in school for over 10 years. I even considered going professional but found accidentally stumbled upon design. I'm now back at playing volleyball (just for fun) every Monday and Wednesday 🏐","Thin-crust pizza is my spiritual food 🍕", "I started playing with Photoshop and After Effects when I was 12. I was a collaborator on a forum for sharing pirate software and films and use to make signs and avatars for my peers. Today I'm a huge supporter for people coming up with original content, and pay for all my software licenses.", "My website has been mostly black, grey and white since it's first version in 2009. This is an experiment in colour and it has several accessibility issues. I'm working on a new, more accessible version. Please feel free to send be a feedback at hey@lucasterra.com","The characteristic I admire the most in a person is their willingness to change their mind about a subject. It brings me hope about our survival as a species.","Besides Brazil, people also access this website from France, US, India and Australia. Thank you for visiting it too :)", "I've been away from facebook since June 2017. My mental health improved a lot since this decision.", "Porguguese author Valter Hugo Mãe says that the concept of humanity translates to him as our cultural-intellectual construction instead of just being born as the animal we are. This means a lot to mee in terms of how to live in society."];

  $('.factbutton').click(function() {

    randomNum = Math.floor(Math.random() * quotes.length);

    $("#quote").text(quotes[randomNum]);
});

});